%* modification 2019-12-23 - update path as data has been moved;

filename source url "https://raw.githubusercontent.com/phuse-org/phuse-scripts/master/data/adam/cdisc/adsl.xpt";
libname source xport ;
data work.adsl ;
	set source.adsl ;
run ;

filename source url "https://raw.githubusercontent.com/phuse-org/phuse-scripts/master/data/adam/cdisc/adpc.xpt" ;
libname source xport ;
data work.adpc ;
	set source.adpc ;
run ;

title1 j=center "(page x of x)";
title2 j=center "Figure 16.2.5-x.x Individual concentration-time profiles";
title3 j=center "by compound, matrix, analyte and [actual/randomised][treatments/group]";
title4 j=center "Analysis Set : PK analysis set";

options nobyline;
PROC SORT
	DATA=WORK.ADPC OUT=WORK.SORTadpc;
	BY USUBJID parcat1 eactm;
RUN;
SYMBOL1
	INTERPOL=JOIN
	HEIGHT=10pt
	VALUE=NONE
	LINE=1
	WIDTH=2

	CV = _STYLE_
;
Axis1
	STYLE=1
	WIDTH=1
	MINOR=NONE
	LABEL=( "Conc (ug/mL)" )


;
Axis2
	STYLE=1
	WIDTH=1
	MINOR=NONE
	LABEL=( "Time (hour)" )


;
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";


PROC GPLOT DATA = WORK.SORTadpc NOCACHE ;
PLOT AVAL * eactm  /
 	VAXIS=AXIS1
	HAXIS=AXIS2
    FRAME;
	BY USUBJID parcat1;
RUN; 


QUIT;
TITLE; FOOTNOTE;
GOPTIONS RESET = SYMBOL;
